import { useCallback, useEffect, useState } from 'react';
import { Eye, Search } from 'lucide-react';
import { getAdminPayment, getAdminReport, listAdminPayments } from '../../utils/adminClient.js';
import { actionClass, DetailDrawer, DetailGrid, formatCurrency, formatDate, inputClass, ReportBody, StatusBadge, TableState, Pagination } from './AdminTableState.jsx';

export default function AdminPayments({ monthKey, onUnauthorized }) {
  const [filters, setFilters] = useState({ query: '', status: '', provider: '', page: 1, pageSize: 20 });
  const [state, setState] = useState({ loading: true, error: '', data: null });
  const [detail, setDetail] = useState(null);
  const [report, setReport] = useState(null);
  const load = useCallback(async () => {
    setState((current) => ({ ...current, loading: true, error: '' }));
    try { setState({ loading: false, error: '', data: await listAdminPayments({ month: monthKey, ...filters }) }); } catch (error) { if (error.status === 401) onUnauthorized(); setState({ loading: false, error: error.message, data: null }); }
  }, [filters, monthKey, onUnauthorized]);
  useEffect(() => { load(); }, [load]);
  const showPayment = async (id) => { try { setDetail(await getAdminPayment(id)); } catch (error) { if (error.status === 401) onUnauthorized(); setState((current) => ({ ...current, error: error.message })); } };
  const showReport = async (id) => { if (!id) return; try { setReport(await getAdminReport(id)); } catch (error) { if (error.status === 401) onUnauthorized(); setState((current) => ({ ...current, error: error.message })); } };

  return (
    <section className="rounded-3xl border border-[#2C2C2C]/10 bg-[#F5F0E6] p-6 shadow-sm md:p-8">
      <div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-serif text-2xl font-bold text-[#2C2C2C]">付款订单</h2><p className="mt-1 text-sm text-[#2C2C2C]/55">微信、支付宝直连订单状态和生成内容</p></div><div className="flex flex-wrap gap-2"><label className="relative"><span className="sr-only">搜索订单</span><Search size={16} className="absolute left-3 top-3 text-[#2C2C2C]/40" /><input className={`${inputClass} pl-9`} value={filters.query} onChange={(event) => setFilters((current) => ({ ...current, query: event.target.value, page: 1 }))} placeholder="订单号 / 用户 / 序号" /></label><select className={inputClass} value={filters.provider} onChange={(event) => setFilters((current) => ({ ...current, provider: event.target.value, page: 1 }))}><option value="">全部渠道</option><option value="wechat">微信支付</option><option value="alipay">支付宝</option></select><select className={inputClass} value={filters.status} onChange={(event) => setFilters((current) => ({ ...current, status: event.target.value, page: 1 }))}><option value="">全部状态</option><option value="paid">已付款</option><option value="pending">待付款</option><option value="closed">已关闭</option></select><button type="button" className={actionClass} onClick={load}>刷新</button></div></div>
      <div className="mt-6 overflow-x-auto rounded-2xl border border-[#2C2C2C]/8 bg-white"><TableState loading={state.loading} error={state.error} empty={!state.data?.items?.length} onRetry={load}><table className="min-w-[1050px] w-full text-left text-sm"><thead className="bg-[#2C2C2C]/[.03] text-xs text-[#2C2C2C]/55"><tr><th className="px-4 py-3">订单号</th><th className="px-4 py-3">用户</th><th className="px-4 py-3">渠道</th><th className="px-4 py-3">金额</th><th className="px-4 py-3">状态</th><th className="px-4 py-3">付款时间</th><th className="px-4 py-3 text-right">操作</th></tr></thead><tbody>{state.data.items.map((item) => <tr key={item.id} className="border-t border-[#2C2C2C]/[.06] text-[#2C2C2C]/80"><td className="px-4 py-4"><p className="font-mono text-xs">{item.id}</p><p className="mt-1 text-xs text-[#2C2C2C]/45">序号 {item.sequence || '—'}</p></td><td className="px-4 py-4 font-bold">{item.userName || '未关联用户'}</td><td className="px-4 py-4">{item.provider === 'wechat' ? '微信支付' : '支付宝'}</td><td className="px-4 py-4 font-bold text-[#B22222]">{formatCurrency(item.payableMinor, item.currency)}</td><td className="px-4 py-4"><StatusBadge status={item.status} /></td><td className="px-4 py-4 text-xs">{formatDate(item.paidAt || item.createdAt)}</td><td className="px-4 py-4"><div className="flex justify-end gap-2"><button type="button" onClick={() => showPayment(item.id)} className="rounded-lg border border-[#2C2C2C]/10 bg-white px-3 py-2 text-xs font-bold">订单详情</button><button type="button" disabled={!item.reportId} onClick={() => showReport(item.reportId)} className="inline-flex items-center gap-1 rounded-lg bg-[#B22222] px-3 py-2 text-xs font-bold text-white disabled:bg-[#2C2C2C]/20"><Eye size={14} />查看生成内容</button></div></td></tr>)}</tbody></table><div className="px-4 pb-4"><Pagination page={state.data.page} pageSize={state.data.pageSize} total={state.data.total} onPage={(page) => setFilters((current) => ({ ...current, page }))} /></div></TableState></div>
      <DetailDrawer title={detail ? `订单：${detail.id}` : ''} subtitle="付款订单详情" onClose={() => setDetail(null)}>{detail && <DetailGrid items={[["用户", detail.userName], ["订单号", detail.id], ["支付渠道", detail.provider === 'wechat' ? '微信支付' : '支付宝'], ["订单状态", detail.status], ["应付金额", formatCurrency(detail.payableMinor, detail.currency)], ["平台流水号", detail.gatewayOrderNo], ["创建时间", formatDate(detail.createdAt)], ["付款时间", formatDate(detail.paidAt)], ["关联报告", detail.reportId || '尚未生成']]} />}</DetailDrawer>
      <DetailDrawer title={report ? (report.reportTitle || '生成内容') : ''} subtitle={report ? `序号 ${report.sequence}` : ''} onClose={() => setReport(null)}><ReportBody report={report} /></DetailDrawer>
    </section>
  );
}
